In [1]:
import pandas as pd

In [2]:
geolocation = pd.read_csv("../archive/olist_geolocation_dataset.csv")

In [3]:
geolocation.shape

(1000163, 5)

In [4]:
geolocation.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

In [5]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [6]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [7]:
geolocation.describe()

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

In [8]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [9]:
geolocation.duplicated().sum()

np.int64(261831)

In [10]:
geolocation[geolocation.duplicated()].head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP

In [11]:
geolocation = geolocation.drop_duplicates()

In [12]:
geolocation.shape

(738332, 5)

Before: 1,000,163 rows

After: 738,332 rows

Removed: 261,831 duplicate rows

In [13]:
geolocation.duplicated().sum()

np.int64(0)

In [14]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
Index: 738332 entries, 0 to 1000161
Data columns (total 5 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   geolocation_zip_code_prefix  738332 non-null  int64
 1   geolocation_lat              738332 non-null  float64
 2   geolocation_lng              738332 non-null  float64
 3   geolocation_city             738332 non-null  object
 4   geolocation_state            738332 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 33.8+ MB

In [15]:
geolocation[["geolocation_lat", "geolocation_lng"]].describe()

       geolocation_lat  geolocation_lng
count    738332.000000    738332.000000
mean        -20.998353       -46.461098
std           5.892315         4.393705
min         -36.605374      -101.466766
25%         -23.603061       -48.867822
50%         -22.873588       -46.647278
75%         -19.923336       -43.836974
max          45.065933       121.105394

In [16]:
geolocation[
    (geolocation["geolocation_lat"] > 5) |
    (geolocation["geolocation_lat"] < -35) |
    (geolocation["geolocation_lng"] > -30) |
    (geolocation["geolocation_lng"] < -75)
].shape

(25, 5)

In [17]:
geolocation[
    (geolocation["geolocation_lat"] > 5) |
    (geolocation["geolocation_lat"] < -35) |
    (geolocation["geolocation_lng"] > -30) |
    (geolocation["geolocation_lng"] < -75)
]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
387565,18243,28.008978,-15.536867,bom retiro da esperanca,SP
513631,28165,41.614052,-8.411675,vila nova de campos,RJ
513754,28155,42.439286,13.820214,santa maria,RJ
514429,28333,38.381672,-6.328200,raposo,RJ
516682,28595,43.684961,-7.411080,portela,RJ
538512,29654,29.409252,-98.484121,santo antônio do canaã,ES
538557,29654,21.657547,-101.466766,santo antonio do canaa,ES
585242,35179,25.995203,-98.078544,santana do paraíso,MG
585260,35179,25.995245,-98.078533,santana do paraiso,MG
695377,45936,38.323939,-6.775035,itabatan,BA
697048,46560,38.991963,-4.947823,ibiajara,BA
698466,47310,38.268205,-7.803886,santana do sobrado,BA
727755,57319,45.065933,9.341528,pau d'arco,AL
732362,58441,41.385328,-8.717342,são josé da mata,PB
769333,68275,41.146203,-8.577855,porto trombetas,PA
769351,68275,42.166805,-6.898531,porto trombetas,PA
769391,68275,42.167251,-6.898559,porto trombetas,PA
769924,68379,38.713128,-9.135741,castelo dos sonhos,PA
770534,68447,42.428884,-6.873344,vila dos cabanos,PA
822529,78131,38.816816,-9.394625,varzea grande,MT
860562,83252,42.184003,-8.723762,ilha dos valadares,PR
865611,83810,39.057629,-9.400037,areia branca dos assis,PR
965687,95130,14.585073,121.105394,santa lucia do piai,RS
992584,98780,-36.605374,-64.283946,santa rosa,RS
993075,98780,-36.603837,-64.287433,santa rosa,RS

In [18]:
geolocation = geolocation[
    (geolocation["geolocation_lat"] <= 5) &
    (geolocation["geolocation_lat"] >= -35) &
    (geolocation["geolocation_lng"] <= -30) &
    (geolocation["geolocation_lng"] >= -75)
]

In [20]:
geolocation.shape

(738307, 5)

In [21]:
geolocation = geolocation.reset_index(drop=True)

In [22]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [23]:
geolocation.to_csv("../cleaned_datasets/cleaned_geolocation.csv")